version: "3.8"

services:
  #--------------------------------------------------------
  # Server services
  #--------------------------------------------------------
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - php
    networks:
      - game-hub

  #--------------------------------------------------------
  # Backend services
  #--------------------------------------------------------
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    extra_hosts:
      - 'game-hub.test:127.0.0.1'
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - game-hub

  #--------------------------------------------------------
  # Utility servcices
  #--------------------------------------------------------
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - game-hub
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/artisan.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - game-hub

#--------------------------------------------------------
# Networks
#--------------------------------------------------------
networks:
  game-hub:
    name: 'game_hub_network'
